fragment PageParts on Page {
  __typename
  title
  draft
  body
  localize
  created
  lastUpdated
  sha256
}

fragment LocalesParts on Locales {
  __typename
  locales {
    __typename
    code
    name
    nativeName
    direction
    flag
  }
}

fragment PartialsParts on Partials {
  __typename
  name
  content
  sha256
}

fragment HeaderMenuParts on HeaderMenu {
  __typename
  logo
  menuLinks {
    __typename
    url
    isInteral
    localize
    label
    icon
    description
    submenuItem {
      __typename
      subItem {
        __typename
        url
        isInteral
        localize
        label
        description
      }
      nestedMenu {
        __typename
        groupLabel
        submenuChildren {
          __typename
          url
          isInteral
          localize
          label
          description
        }
      }
    }
  }
  sha256
}
