//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  locales: Locales;
  localesConnection: LocalesConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryLocalesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocalesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocalesFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  locales?: InputMaybe<LocalesFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Locales | Folder;

export type Page = Node & Document & {
  __typename?: 'Page';
  title?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  localize?: Maybe<Scalars['Boolean']['output']>;
  created?: Maybe<Scalars['String']['output']>;
  lastUpdated?: Maybe<Scalars['String']['output']>;
  sha256?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PageBodyGridChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyGridChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenGridChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenGridChildrenColumnChildrenFilter>;
};

export type PageBodyGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenGridChildrenFilter>;
};

export type PageBodyGridChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenColumnChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PageBodyGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenColumnChildrenGridChildrenFilter>;
};

export type PageBodyGridChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyGridChildrenColumnChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PageBodyGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenColumnChildrenColumnChildrenFilter>;
};

export type PageBodyGridChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenColumnChildrenFilter>;
};

export type PageBodyGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyGridChildrenColumnFilter>;
};

export type PageBodyGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenFilter>;
};

export type PageBodyColumnChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenGridChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenGridChildrenGridChildrenBoxFilter>;
};

export type PageBodyColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyColumnChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenGridChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenGridChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenGridChildrenBoxChildrenBoxFilter>;
};

export type PageBodyColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenGridChildrenBoxChildrenFilter>;
};

export type PageBodyColumnChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenGridChildrenBoxFilter>;
};

export type PageBodyColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenGridChildrenFilter>;
};

export type PageBodyColumnChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenBoxChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenBoxChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenBoxChildrenGridChildrenBoxFilter>;
};

export type PageBodyColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenBoxChildrenGridChildrenFilter>;
};

export type PageBodyColumnChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyColumnChildrenBoxChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenBoxChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenBoxChildrenBoxChildrenBoxFilter>;
};

export type PageBodyColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenBoxChildrenBoxChildrenFilter>;
};

export type PageBodyColumnChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenBoxChildrenBoxFilter>;
};

export type PageBodyColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenBoxChildrenFilter>;
};

export type PageBodyColumnChildrenFilter = {
  Grid?: InputMaybe<PageBodyColumnChildrenGridFilter>;
  Box?: InputMaybe<PageBodyColumnChildrenBoxFilter>;
};

export type PageBodyColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenBoxChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenGridChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnChildrenColumnFilter>;
};

export type PageBodyBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenFilter = {
  Box?: InputMaybe<PageBodyBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PageBodyBoxChildrenGridFilter>;
  Column?: InputMaybe<PageBodyBoxChildrenColumnFilter>;
};

export type PageBodyBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenFilter>;
};

export type PageBodyFilter = {
  Grid?: InputMaybe<PageBodyGridFilter>;
  Column?: InputMaybe<PageBodyColumnFilter>;
  Box?: InputMaybe<PageBodyBoxFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<PageBodyFilter>;
  localize?: InputMaybe<BooleanFilter>;
  created?: InputMaybe<DatetimeFilter>;
  lastUpdated?: InputMaybe<DatetimeFilter>;
  sha256?: InputMaybe<StringFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type LocalesLocales = {
  __typename?: 'LocalesLocales';
  code: Scalars['String']['output'];
  name: Scalars['String']['output'];
  nativeName: Scalars['String']['output'];
  direction: Scalars['String']['output'];
  flag?: Maybe<Scalars['String']['output']>;
};

export type Locales = Node & Document & {
  __typename?: 'Locales';
  locales?: Maybe<Array<Maybe<LocalesLocales>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocalesLocalesFilter = {
  code?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  nativeName?: InputMaybe<StringFilter>;
  direction?: InputMaybe<StringFilter>;
  flag?: InputMaybe<StringFilter>;
};

export type LocalesFilter = {
  locales?: InputMaybe<LocalesLocalesFilter>;
};

export type LocalesConnectionEdges = {
  __typename?: 'LocalesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Locales>;
};

export type LocalesConnection = Connection & {
  __typename?: 'LocalesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocalesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateLocales: Locales;
  createLocales: Locales;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateLocalesArgs = {
  relativePath: Scalars['String']['input'];
  params: LocalesMutation;
};


export type MutationCreateLocalesArgs = {
  relativePath: Scalars['String']['input'];
  params: LocalesMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  locales?: InputMaybe<LocalesMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  locales?: InputMaybe<LocalesMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  localize?: InputMaybe<Scalars['Boolean']['input']>;
  created?: InputMaybe<Scalars['String']['input']>;
  lastUpdated?: InputMaybe<Scalars['String']['input']>;
  sha256?: InputMaybe<Scalars['String']['input']>;
};

export type LocalesLocalesMutation = {
  code?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  nativeName?: InputMaybe<Scalars['String']['input']>;
  direction?: InputMaybe<Scalars['String']['input']>;
  flag?: InputMaybe<Scalars['String']['input']>;
};

export type LocalesMutation = {
  locales?: InputMaybe<Array<InputMaybe<LocalesLocalesMutation>>>;
};

export type PagePartsFragment = { __typename: 'Page', title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null };

export type LocalesPartsFragment = { __typename: 'Locales', locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LocalesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LocalesQuery = { __typename?: 'Query', locales: { __typename: 'Locales', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null } };

export type LocalesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocalesFilter>;
}>;


export type LocalesConnectionQuery = { __typename?: 'Query', localesConnection: { __typename?: 'LocalesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LocalesConnectionEdges', cursor: string, node?: { __typename: 'Locales', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  draft
  body
  localize
  created
  lastUpdated
  sha256
}
    `;
export const LocalesPartsFragmentDoc = gql`
    fragment LocalesParts on Locales {
  __typename
  locales {
    __typename
    code
    name
    nativeName
    direction
    flag
  }
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const LocalesDocument = gql`
    query locales($relativePath: String!) {
  locales(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocalesParts
  }
}
    ${LocalesPartsFragmentDoc}`;
export const LocalesConnectionDocument = gql`
    query localesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocalesFilter) {
  localesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocalesParts
      }
    }
  }
}
    ${LocalesPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    locales(variables: LocalesQueryVariables, options?: C): Promise<{data: LocalesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesQueryVariables, query: string}> {
        return requester<{data: LocalesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesQueryVariables, query: string}, LocalesQueryVariables>(LocalesDocument, variables, options);
      },
    localesConnection(variables?: LocalesConnectionQueryVariables, options?: C): Promise<{data: LocalesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesConnectionQueryVariables, query: string}> {
        return requester<{data: LocalesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesConnectionQueryVariables, query: string}, LocalesConnectionQueryVariables>(LocalesConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/content",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  