//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  locales: Locales;
  localesConnection: LocalesConnection;
  partials: Partials;
  partialsConnection: PartialsConnection;
  headerMenu: HeaderMenu;
  headerMenuConnection: HeaderMenuConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryLocalesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLocalesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocalesFilter>;
};


export type QueryPartialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartialsFilter>;
};


export type QueryHeaderMenuArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeaderMenuConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeaderMenuFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  locales?: InputMaybe<LocalesFilter>;
  partials?: InputMaybe<PartialsFilter>;
  headerMenu?: InputMaybe<HeaderMenuFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Locales | Partials | HeaderMenu | Folder;

export type Page = Node & Document & {
  __typename?: 'Page';
  title?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  localize?: Maybe<Scalars['Boolean']['output']>;
  created?: Maybe<Scalars['String']['output']>;
  lastUpdated?: Maybe<Scalars['String']['output']>;
  sha256?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PartialsContentGridChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentGridChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenGridChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenGridChildrenColumnChildrenFilter>;
};

export type PartialsContentGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenGridChildrenFilter>;
};

export type PartialsContentGridChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenColumnChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PartialsContentGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenColumnChildrenGridChildrenFilter>;
};

export type PartialsContentGridChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentGridChildrenColumnChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenColumnChildrenColumnChildrenFilter>;
};

export type PartialsContentGridChildrenColumnChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenColumnChildrenFilter>;
};

export type PageBodyGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenColumnFilter>;
};

export type PageBodyGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyGridChildrenFilter>;
};

export type PartialsContentColumnChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenGridChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenGridChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenGridChildrenGridChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentColumnChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenGridChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenGridChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenGridChildrenBoxChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenGridChildrenBoxChildrenFilter>;
};

export type PartialsContentColumnChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenGridChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenGridChildrenFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenBoxChildrenGridChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenBoxChildrenGridChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenBoxChildrenGridChildrenFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenBoxChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenBoxChildrenBoxChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentColumnChildrenBoxChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenBoxChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenBoxChildrenBoxFilter>;
};

export type PartialsContentColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenBoxChildrenFilter>;
};

export type PageBodyColumnChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenBoxFilter>;
};

export type PageBodyColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenGridChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<RichTextFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenColumnChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenColumnChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenColumnChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnChildrenColumnFilter>;
};

export type PartialsContentBoxChildrenColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenColumnChildrenFilter>;
};

export type PageBodyBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnFilter>;
};

export type PageBodyBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PageBodyBoxChildrenFilter>;
};

export type PageBodyFilter = {
  Grid?: InputMaybe<PageBodyGridFilter>;
  Column?: InputMaybe<PageBodyColumnFilter>;
  Box?: InputMaybe<PageBodyBoxFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  draft?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<PageBodyFilter>;
  localize?: InputMaybe<BooleanFilter>;
  created?: InputMaybe<DatetimeFilter>;
  lastUpdated?: InputMaybe<DatetimeFilter>;
  sha256?: InputMaybe<StringFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type LocalesLocales = {
  __typename?: 'LocalesLocales';
  code: Scalars['String']['output'];
  name: Scalars['String']['output'];
  nativeName: Scalars['String']['output'];
  direction: Scalars['String']['output'];
  flag?: Maybe<Scalars['String']['output']>;
};

export type Locales = Node & Document & {
  __typename?: 'Locales';
  locales?: Maybe<Array<Maybe<LocalesLocales>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LocalesLocalesFilter = {
  code?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  nativeName?: InputMaybe<StringFilter>;
  direction?: InputMaybe<StringFilter>;
  flag?: InputMaybe<StringFilter>;
};

export type LocalesFilter = {
  locales?: InputMaybe<LocalesLocalesFilter>;
};

export type LocalesConnectionEdges = {
  __typename?: 'LocalesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Locales>;
};

export type LocalesConnection = Connection & {
  __typename?: 'LocalesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LocalesConnectionEdges>>>;
};

export type Partials = Node & Document & {
  __typename?: 'Partials';
  name?: Maybe<Scalars['String']['output']>;
  content?: Maybe<Scalars['JSON']['output']>;
  sha256?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartialsContentGridChildrenFilter = {
  Grid?: InputMaybe<PartialsContentGridChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentGridChildrenColumnFilter>;
};

export type PartialsContentGridFilter = {
  class?: InputMaybe<StringFilter>;
  colMinWidth?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentGridChildrenFilter>;
};

export type PartialsContentColumnChildrenFilter = {
  Grid?: InputMaybe<PartialsContentColumnChildrenGridFilter>;
  Box?: InputMaybe<PartialsContentColumnChildrenBoxFilter>;
};

export type PartialsContentColumnFilter = {
  class?: InputMaybe<StringFilter>;
  colMaxWidth?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentColumnChildrenFilter>;
};

export type PartialsContentBoxChildrenFilter = {
  Box?: InputMaybe<PartialsContentBoxChildrenBoxFilter>;
  Grid?: InputMaybe<PartialsContentBoxChildrenGridFilter>;
  Column?: InputMaybe<PartialsContentBoxChildrenColumnFilter>;
};

export type PartialsContentBoxFilter = {
  class?: InputMaybe<StringFilter>;
  bgImage?: InputMaybe<StringFilter>;
  children?: InputMaybe<PartialsContentBoxChildrenFilter>;
};

export type PartialsContentFilter = {
  Grid?: InputMaybe<PartialsContentGridFilter>;
  Column?: InputMaybe<PartialsContentColumnFilter>;
  Box?: InputMaybe<PartialsContentBoxFilter>;
};

export type PartialsFilter = {
  name?: InputMaybe<StringFilter>;
  content?: InputMaybe<PartialsContentFilter>;
  sha256?: InputMaybe<StringFilter>;
};

export type PartialsConnectionEdges = {
  __typename?: 'PartialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partials>;
};

export type PartialsConnection = Connection & {
  __typename?: 'PartialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartialsConnectionEdges>>>;
};

export type HeaderMenuMenuLinksSubmenuItemSubItem = {
  __typename?: 'HeaderMenuMenuLinksSubmenuItemSubItem';
  url?: Maybe<Scalars['String']['output']>;
  isInteral?: Maybe<Scalars['Boolean']['output']>;
  localize?: Maybe<Scalars['Boolean']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren = {
  __typename?: 'HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren';
  url?: Maybe<Scalars['String']['output']>;
  isInteral?: Maybe<Scalars['Boolean']['output']>;
  localize?: Maybe<Scalars['Boolean']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenu = {
  __typename?: 'HeaderMenuMenuLinksSubmenuItemNestedMenu';
  groupLabel?: Maybe<Scalars['String']['output']>;
  submenuChildren?: Maybe<Array<Maybe<HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren>>>;
};

export type HeaderMenuMenuLinksSubmenuItem = {
  __typename?: 'HeaderMenuMenuLinksSubmenuItem';
  subItem?: Maybe<Array<Maybe<HeaderMenuMenuLinksSubmenuItemSubItem>>>;
  nestedMenu?: Maybe<Array<Maybe<HeaderMenuMenuLinksSubmenuItemNestedMenu>>>;
};

export type HeaderMenuMenuLinks = {
  __typename?: 'HeaderMenuMenuLinks';
  url?: Maybe<Scalars['String']['output']>;
  isInteral?: Maybe<Scalars['Boolean']['output']>;
  localize?: Maybe<Scalars['Boolean']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  submenuItem?: Maybe<HeaderMenuMenuLinksSubmenuItem>;
};

export type HeaderMenu = Node & Document & {
  __typename?: 'HeaderMenu';
  logo?: Maybe<Scalars['String']['output']>;
  menuLinks?: Maybe<Array<Maybe<HeaderMenuMenuLinks>>>;
  sha256?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeaderMenuMenuLinksSubmenuItemSubItemFilter = {
  url?: InputMaybe<StringFilter>;
  isInteral?: InputMaybe<BooleanFilter>;
  localize?: InputMaybe<BooleanFilter>;
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildrenFilter = {
  url?: InputMaybe<StringFilter>;
  isInteral?: InputMaybe<BooleanFilter>;
  localize?: InputMaybe<BooleanFilter>;
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenuFilter = {
  groupLabel?: InputMaybe<StringFilter>;
  submenuChildren?: InputMaybe<HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildrenFilter>;
};

export type HeaderMenuMenuLinksSubmenuItemFilter = {
  subItem?: InputMaybe<HeaderMenuMenuLinksSubmenuItemSubItemFilter>;
  nestedMenu?: InputMaybe<HeaderMenuMenuLinksSubmenuItemNestedMenuFilter>;
};

export type HeaderMenuMenuLinksFilter = {
  url?: InputMaybe<StringFilter>;
  isInteral?: InputMaybe<BooleanFilter>;
  localize?: InputMaybe<BooleanFilter>;
  label?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  submenuItem?: InputMaybe<HeaderMenuMenuLinksSubmenuItemFilter>;
};

export type HeaderMenuFilter = {
  logo?: InputMaybe<ImageFilter>;
  menuLinks?: InputMaybe<HeaderMenuMenuLinksFilter>;
  sha256?: InputMaybe<StringFilter>;
};

export type HeaderMenuConnectionEdges = {
  __typename?: 'HeaderMenuConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HeaderMenu>;
};

export type HeaderMenuConnection = Connection & {
  __typename?: 'HeaderMenuConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeaderMenuConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateLocales: Locales;
  createLocales: Locales;
  updatePartials: Partials;
  createPartials: Partials;
  updateHeaderMenu: HeaderMenu;
  createHeaderMenu: HeaderMenu;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateLocalesArgs = {
  relativePath: Scalars['String']['input'];
  params: LocalesMutation;
};


export type MutationCreateLocalesArgs = {
  relativePath: Scalars['String']['input'];
  params: LocalesMutation;
};


export type MutationUpdatePartialsArgs = {
  relativePath: Scalars['String']['input'];
  params: PartialsMutation;
};


export type MutationCreatePartialsArgs = {
  relativePath: Scalars['String']['input'];
  params: PartialsMutation;
};


export type MutationUpdateHeaderMenuArgs = {
  relativePath: Scalars['String']['input'];
  params: HeaderMenuMutation;
};


export type MutationCreateHeaderMenuArgs = {
  relativePath: Scalars['String']['input'];
  params: HeaderMenuMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  locales?: InputMaybe<LocalesMutation>;
  partials?: InputMaybe<PartialsMutation>;
  headerMenu?: InputMaybe<HeaderMenuMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  locales?: InputMaybe<LocalesMutation>;
  partials?: InputMaybe<PartialsMutation>;
  headerMenu?: InputMaybe<HeaderMenuMutation>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  localize?: InputMaybe<Scalars['Boolean']['input']>;
  created?: InputMaybe<Scalars['String']['input']>;
  lastUpdated?: InputMaybe<Scalars['String']['input']>;
  sha256?: InputMaybe<Scalars['String']['input']>;
};

export type LocalesLocalesMutation = {
  code?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  nativeName?: InputMaybe<Scalars['String']['input']>;
  direction?: InputMaybe<Scalars['String']['input']>;
  flag?: InputMaybe<Scalars['String']['input']>;
};

export type LocalesMutation = {
  locales?: InputMaybe<Array<InputMaybe<LocalesLocalesMutation>>>;
};

export type PartialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['JSON']['input']>;
  sha256?: InputMaybe<Scalars['String']['input']>;
};

export type HeaderMenuMenuLinksSubmenuItemSubItemMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  isInteral?: InputMaybe<Scalars['Boolean']['input']>;
  localize?: InputMaybe<Scalars['Boolean']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildrenMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  isInteral?: InputMaybe<Scalars['Boolean']['input']>;
  localize?: InputMaybe<Scalars['Boolean']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HeaderMenuMenuLinksSubmenuItemNestedMenuMutation = {
  groupLabel?: InputMaybe<Scalars['String']['input']>;
  submenuChildren?: InputMaybe<Array<InputMaybe<HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildrenMutation>>>;
};

export type HeaderMenuMenuLinksSubmenuItemMutation = {
  subItem?: InputMaybe<Array<InputMaybe<HeaderMenuMenuLinksSubmenuItemSubItemMutation>>>;
  nestedMenu?: InputMaybe<Array<InputMaybe<HeaderMenuMenuLinksSubmenuItemNestedMenuMutation>>>;
};

export type HeaderMenuMenuLinksMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  isInteral?: InputMaybe<Scalars['Boolean']['input']>;
  localize?: InputMaybe<Scalars['Boolean']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  submenuItem?: InputMaybe<HeaderMenuMenuLinksSubmenuItemMutation>;
};

export type HeaderMenuMutation = {
  logo?: InputMaybe<Scalars['String']['input']>;
  menuLinks?: InputMaybe<Array<InputMaybe<HeaderMenuMenuLinksMutation>>>;
  sha256?: InputMaybe<Scalars['String']['input']>;
};

export type PagePartsFragment = { __typename: 'Page', title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null };

export type LocalesPartsFragment = { __typename: 'Locales', locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null };

export type PartialsPartsFragment = { __typename: 'Partials', name?: string | null, content?: any | null, sha256?: string | null };

export type HeaderMenuPartsFragment = { __typename: 'HeaderMenu', logo?: string | null, sha256?: string | null, menuLinks?: Array<{ __typename: 'HeaderMenuMenuLinks', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, icon?: string | null, description?: string | null, submenuItem?: { __typename: 'HeaderMenuMenuLinksSubmenuItem', subItem?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemSubItem', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null, nestedMenu?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenu', groupLabel?: string | null, submenuChildren?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null } | null> | null } | null } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title?: string | null, draft?: boolean | null, body?: any | null, localize?: boolean | null, created?: string | null, lastUpdated?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LocalesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LocalesQuery = { __typename?: 'Query', locales: { __typename: 'Locales', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null } };

export type LocalesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LocalesFilter>;
}>;


export type LocalesConnectionQuery = { __typename?: 'Query', localesConnection: { __typename?: 'LocalesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LocalesConnectionEdges', cursor: string, node?: { __typename: 'Locales', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, locales?: Array<{ __typename: 'LocalesLocales', code: string, name: string, nativeName: string, direction: string, flag?: string | null } | null> | null } | null } | null> | null } };

export type PartialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartialsQuery = { __typename?: 'Query', partials: { __typename: 'Partials', id: string, name?: string | null, content?: any | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PartialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartialsFilter>;
}>;


export type PartialsConnectionQuery = { __typename?: 'Query', partialsConnection: { __typename?: 'PartialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartialsConnectionEdges', cursor: string, node?: { __typename: 'Partials', id: string, name?: string | null, content?: any | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HeaderMenuQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeaderMenuQuery = { __typename?: 'Query', headerMenu: { __typename: 'HeaderMenu', id: string, logo?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, menuLinks?: Array<{ __typename: 'HeaderMenuMenuLinks', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, icon?: string | null, description?: string | null, submenuItem?: { __typename: 'HeaderMenuMenuLinksSubmenuItem', subItem?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemSubItem', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null, nestedMenu?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenu', groupLabel?: string | null, submenuChildren?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null } | null> | null } | null } | null> | null } };

export type HeaderMenuConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeaderMenuFilter>;
}>;


export type HeaderMenuConnectionQuery = { __typename?: 'Query', headerMenuConnection: { __typename?: 'HeaderMenuConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeaderMenuConnectionEdges', cursor: string, node?: { __typename: 'HeaderMenu', id: string, logo?: string | null, sha256?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, menuLinks?: Array<{ __typename: 'HeaderMenuMenuLinks', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, icon?: string | null, description?: string | null, submenuItem?: { __typename: 'HeaderMenuMenuLinksSubmenuItem', subItem?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemSubItem', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null, nestedMenu?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenu', groupLabel?: string | null, submenuChildren?: Array<{ __typename: 'HeaderMenuMenuLinksSubmenuItemNestedMenuSubmenuChildren', url?: string | null, isInteral?: boolean | null, localize?: boolean | null, label?: string | null, description?: string | null } | null> | null } | null> | null } | null } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  draft
  body
  localize
  created
  lastUpdated
  sha256
}
    `;
export const LocalesPartsFragmentDoc = gql`
    fragment LocalesParts on Locales {
  __typename
  locales {
    __typename
    code
    name
    nativeName
    direction
    flag
  }
}
    `;
export const PartialsPartsFragmentDoc = gql`
    fragment PartialsParts on Partials {
  __typename
  name
  content
  sha256
}
    `;
export const HeaderMenuPartsFragmentDoc = gql`
    fragment HeaderMenuParts on HeaderMenu {
  __typename
  logo
  menuLinks {
    __typename
    url
    isInteral
    localize
    label
    icon
    description
    submenuItem {
      __typename
      subItem {
        __typename
        url
        isInteral
        localize
        label
        description
      }
      nestedMenu {
        __typename
        groupLabel
        submenuChildren {
          __typename
          url
          isInteral
          localize
          label
          description
        }
      }
    }
  }
  sha256
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const LocalesDocument = gql`
    query locales($relativePath: String!) {
  locales(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LocalesParts
  }
}
    ${LocalesPartsFragmentDoc}`;
export const LocalesConnectionDocument = gql`
    query localesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LocalesFilter) {
  localesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LocalesParts
      }
    }
  }
}
    ${LocalesPartsFragmentDoc}`;
export const PartialsDocument = gql`
    query partials($relativePath: String!) {
  partials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartialsParts
  }
}
    ${PartialsPartsFragmentDoc}`;
export const PartialsConnectionDocument = gql`
    query partialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartialsFilter) {
  partialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartialsParts
      }
    }
  }
}
    ${PartialsPartsFragmentDoc}`;
export const HeaderMenuDocument = gql`
    query headerMenu($relativePath: String!) {
  headerMenu(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeaderMenuParts
  }
}
    ${HeaderMenuPartsFragmentDoc}`;
export const HeaderMenuConnectionDocument = gql`
    query headerMenuConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeaderMenuFilter) {
  headerMenuConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeaderMenuParts
      }
    }
  }
}
    ${HeaderMenuPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    locales(variables: LocalesQueryVariables, options?: C): Promise<{data: LocalesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesQueryVariables, query: string}> {
        return requester<{data: LocalesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesQueryVariables, query: string}, LocalesQueryVariables>(LocalesDocument, variables, options);
      },
    localesConnection(variables?: LocalesConnectionQueryVariables, options?: C): Promise<{data: LocalesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesConnectionQueryVariables, query: string}> {
        return requester<{data: LocalesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LocalesConnectionQueryVariables, query: string}, LocalesConnectionQueryVariables>(LocalesConnectionDocument, variables, options);
      },
    partials(variables: PartialsQueryVariables, options?: C): Promise<{data: PartialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartialsQueryVariables, query: string}> {
        return requester<{data: PartialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartialsQueryVariables, query: string}, PartialsQueryVariables>(PartialsDocument, variables, options);
      },
    partialsConnection(variables?: PartialsConnectionQueryVariables, options?: C): Promise<{data: PartialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartialsConnectionQueryVariables, query: string}> {
        return requester<{data: PartialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartialsConnectionQueryVariables, query: string}, PartialsConnectionQueryVariables>(PartialsConnectionDocument, variables, options);
      },
    headerMenu(variables: HeaderMenuQueryVariables, options?: C): Promise<{data: HeaderMenuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderMenuQueryVariables, query: string}> {
        return requester<{data: HeaderMenuQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderMenuQueryVariables, query: string}, HeaderMenuQueryVariables>(HeaderMenuDocument, variables, options);
      },
    headerMenuConnection(variables?: HeaderMenuConnectionQueryVariables, options?: C): Promise<{data: HeaderMenuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderMenuConnectionQueryVariables, query: string}> {
        return requester<{data: HeaderMenuConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeaderMenuConnectionQueryVariables, query: string}, HeaderMenuConnectionQueryVariables>(HeaderMenuConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "/api/content",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  