name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_run:
    workflows: [Translate]
    types:
      - completed
  workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    env:
      DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
      MS_REDIRECT_URI: ${{ secrets.MS_REDIRECT_URI }}
      MS_POST_LOGOUT_REDIRECT_URI: ${{ secrets.MS_POST_LOGOUT_REDIRECT_URI }}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      GITHUB_OWNER: ${{ secrets.OWNER }}
      GITHUB_REPO: ${{ secrets.REPO }}
      GITHUB_BRANCH: ${{ secrets.BRANCH }}
      PUBLIC_IS_LOCAL: ${{ secrets.PUBLIC_IS_LOCAL }}
      KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
      KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      S3_ACCOUNT_ID: ${{ secrets.S3_ACCOUNT_ID }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      MS_URL: ${{ secrets.MS_URL }}
      MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
      MS_APP_ID: ${{ secrets.MS_APP_ID }}
      MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
      MS_SESSION_SECRET: ${{ secrets.MS_SESSION_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Tina
        run: npm run build
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
